### ISSUE TITLE
Automate private repositories of different providers to install apps via HTTP authentication

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet-e2e#51]
## Task
Automate via Cypress installation of application held on private repositories via `HTTP auth` providing username and password.
This ticket will be used as the main one for the different PRs needed.

Private repos/QASE cases involved:

- [x] [FLEET-6](https://app.qase.io/case/FLEET-6)  (Gitlab private repo http auth ) --> PR: https://github.com/rancher/fleet-e2e/pull/54
- [x] [FLEET-7](https://app.qase.io/case/FLEET-7) (Bitbucket private repo http auth) --> PR: https://github.com/rancher/fleet-e2e/pull/61
- [x] [FLEET-8](https://app.qase.io/case/FLEET-8) (Github private repo http auth) --> PR: https://github.com/rancher/fleet-e2e/pull/62
- [x] [FLEET-98](https://app.qase.io/case/FLEET-98) (Azure private repo http auth) --> PR: https://github.com/rancher/fleet-e2e/pull/77

**Comment by mmartin24** [comment]
All tasks completed. Closing issue.
