### ISSUE TITLE
Automate private repositories of different providers to install apps via SSH authentication

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet-e2e#79]
## Task
Automate via Cypress installation of application held on private repositories via `SSH auth` providing private and public keys.
This ticket will be used as the main one for the different PRs needed.

Private repos/QASE cases involved:

- [ ] [FLEET-2](https://app.qase.io/case/FLEET-2)  (Gitlab private repo ssh auth ) --> PR: 
- [ ] [FLEET-3](https://app.qase.io/case/FLEET-3) (Bitbucket private repo ssh auth) --> PR: 
- [ ] [FLEET-4](https://app.qase.io/case/FLEET-4) (Github private repo ssh auth) --> PR: 
- [ ] [FLEET-97](https://app.qase.io/case/FLEET-97) (Azure private repo ssh auth) --> PR:
